global:
  scrape_interval: 15s  # Adjust as needed

scrape_configs:
  - job_name: 'stock_prediction_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']  # Target FastAPI service

