name: CI/CD for FastAPI Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installed directly from the root directory

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      run: |
        pip install pytest pytest-mock  # Install pytest and mock for testing
        pytest test_api.py  # Run tests located in the root directory

    - name: Build Docker image
      run: |
        docker build -t aleksandrarancic/myapi:latest .  # Adjust with your username

    - name: Login to Docker Hub
      run: |
        echo "Stock@Investigations2024.MLOps" | docker login -u "aleksandrarancic" --password-stdin

    - name: Push Docker image
      run: |
        docker push aleksandrarancic/myapi:latest  # Push to your Docker Hub repository
