name: Stock Prediction API CI

on:
  push:
    branches: [ "main" ]  # or "master", depending on your branch
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repo
    - uses: actions/checkout@v3

    # Step 2: Set up Python 3.10 (or any version you are using)
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install the required dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Lint the code with flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Run tests with pytest
    - name: Test with pytest
      run: |
        pytest

    # Step 6: Ensure the model is present in the correct directory
    - name: Check for LSTM Model File
      run: |
        if [ ! -f models/lstm_model.h5 ]; then
          echo "Model file lstm_model.h5 is missing!" && exit 1;
        fi
